from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(VendorUser)
# admin.site.register(Offers)
admin.site.register(Staff)
admin.site.register(StaffAttendance)
admin.site.register(Chairs)
admin.site.register(Appointment)
admin.site.register(Category)
admin.site.register(Services)
admin.site.register(Manager)
admin.site.register(MembershipType)
admin.site.register(MembershipTypeService)
admin.site.register(CustomerMembership)
admin.site.register(CancelledAppointment)
admin.site.register(AppointmentRemarks)
admin.site.register(CustomerTable)
# admin.site.register(GiftCard)
admin.site.register(Sale)
admin.site.register(SalonRequest)
admin.site.register(SalonImage)
admin.site.register(SellingInventory)
admin.site.register(UseInventory)
admin.site.register(Sell)
admin.site.register(Brand)
admin.site.register(PackageRequest)
admin.site.register(CurrentUseInventory)
admin.site.register(Dailyupdaterequest)
admin.site.register(Clientworkphotosrequest)
admin.site.register(DailyupdaterequestNotification)
admin.site.register(ClientworkphotosrequestNotification)
