from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(Services)
admin.site.register(Blog)
admin.site.register(Area)
admin.site.register(City)
admin.site.register(FAQ)
admin.site.register(Salon)
admin.site.register(SalonMulImage)
admin.site.register(Review)
admin.site.register(Offer)
admin.site.register(CategoryModel)
admin.site.register(Log)
admin.site.register(MasterCategory)
admin.site.register(MasterService)
admin.site.register(SalonClientImage)
admin.site.register(RegisterSalon)
admin.site.register(SalonUser)
admin.site.register(AuditLog)
admin.site.register(BlogCategory)
admin.site.register(SEO)
admin.site.register(BlogImage)
admin.site.register(Email)
admin.site.register(DailyUpdate)
admin.site.register(NationalOffer)
admin.site.register(NationalCategory)
admin.site.register(Contact)
admin.site.register(ChatData)
admin.site.register(CustomUserPermissions)
admin.site.register(SalonOfferTag)
admin.site.register(Package)
admin.site.register(NationalHeroOffer)
admin.site.register(Rating)
admin.site.register(Featurethisweek)
admin.site.register(salonprofileoffer)
admin.site.register(PopularLocation)
admin.site.register(MasterProduct)
admin.site.register(ProductOfSalon)
admin.site.register(OfferNewPage)
admin.site.register(SalonReport)
admin.site.register(FeedbackSalon)
admin.site.register(BookingNew)
admin.site.register(UserCoinWallet)
admin.site.register(MasterOverview)
admin.site.register(SerivceDetailStepImage)
admin.site.register(ServiceDetailSwipperlImage)
admin.site.register(ServiceDetail)
admin.site.register(AddSpend)
admin.site.register(Coupons)
admin.site.register(booknowLog)
admin.site.register(Lead)
admin.site.register(convertedleads)
admin.site.register(inquiryleads)
# admin.site.register(CallRecording)

# salon categoiries
admin.site.register(SalonBridal)
admin.site.register(SalonMakeUp)
admin.site.register(SalonUnisex)
admin.site.register(SalonTopRated)
admin.site.register(SalonAcademy)
admin.site.register(SalonFemaleBeautyParlour)
admin.site.register(SalonKidsSpecial)
admin.site.register(SalonMale)

